<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="7" passed="3" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-06-01T18:15:42 CEST" name="Heartbeat" finished-at="2021-06-01T18:16:00 CEST" duration-ms="17886">
    <groups>
      <group name="heartbeat">
        <method signature="InputHappyPathIntegerAndValidateResult.validateHappyPathIntegerAndResult()[pri:0, instance:tests.InputHappyPathIntegerAndValidateResult@22ef9844]" name="validateHappyPathIntegerAndResult" class="tests.InputHappyPathIntegerAndValidateResult"/>
        <method signature="NaviagateToHomePageAndValidateStrings.validateElementsonHomePage()[pri:0, instance:tests.NaviagateToHomePageAndValidateStrings@1a18644]" name="validateElementsonHomePage" class="tests.NaviagateToHomePageAndValidateStrings"/>
        <method signature="NegativeTestInputDecimal.validateStringInputError()[pri:0, instance:tests.NegativeTestInputDecimal@5acf93bb]" name="validateStringInputError" class="tests.NegativeTestInputDecimal"/>
        <method signature="NegativeTestInputNegativeInteger.validateStringInputError()[pri:0, instance:tests.NegativeTestInputNegativeInteger@7e7be63f]" name="validateStringInputError" class="tests.NegativeTestInputNegativeInteger"/>
        <method signature="NegativeTestInputString.validateStringInputError()[pri:0, instance:tests.NegativeTestInputString@6cd28fa7]" name="validateStringInputError" class="tests.NegativeTestInputString"/>
      </group> <!-- heartbeat -->
    </groups>
    <test started-at="2021-06-01T18:15:42 CEST" name="FactorialTests" finished-at="2021-06-01T18:16:00 CEST" duration-ms="17886">
      <class name="tests.NegativeTestInputString">
        <test-method is-config="true" signature="setup()[pri:0, instance:tests.NegativeTestInputString@6cd28fa7]" started-at="2021-06-01T18:15:57 CEST" name="setup" finished-at="2021-06-01T18:15:59 CEST" duration-ms="1946" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="validateStringInputError()[pri:0, instance:tests.NegativeTestInputString@6cd28fa7]" started-at="2021-06-01T18:15:59 CEST" name="validateStringInputError" description="Verify that inputing string into input field is displaying expected error " finished-at="2021-06-01T18:16:00 CEST" duration-ms="450" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateStringInputError -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.NegativeTestInputString@6cd28fa7]" started-at="2021-06-01T18:16:00 CEST" name="tearDown" finished-at="2021-06-01T18:16:00 CEST" duration-ms="686" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.NegativeTestInputString -->
      <class name="tests.NegativeTestInputDecimal">
        <test-method is-config="true" signature="setup()[pri:0, instance:tests.NegativeTestInputDecimal@5acf93bb]" started-at="2021-06-01T18:15:51 CEST" name="setup" finished-at="2021-06-01T18:15:53 CEST" duration-ms="2030" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="validateStringInputError()[pri:0, instance:tests.NegativeTestInputDecimal@5acf93bb]" started-at="2021-06-01T18:15:53 CEST" name="validateStringInputError" description="Verify that inputing decimal number into input field is displaying expected error " finished-at="2021-06-01T18:15:53 CEST" duration-ms="381" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateStringInputError -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.NegativeTestInputDecimal@5acf93bb]" started-at="2021-06-01T18:15:53 CEST" name="tearDown" finished-at="2021-06-01T18:15:54 CEST" duration-ms="735" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.NegativeTestInputDecimal -->
      <class name="tests.NegativeTestInputNegativeInteger">
        <test-method is-config="true" signature="setup()[pri:0, instance:tests.NegativeTestInputNegativeInteger@7e7be63f]" started-at="2021-06-01T18:15:54 CEST" name="setup" finished-at="2021-06-01T18:15:56 CEST" duration-ms="2104" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="validateStringInputError()[pri:0, instance:tests.NegativeTestInputNegativeInteger@7e7be63f]" started-at="2021-06-01T18:15:56 CEST" name="validateStringInputError" description="Verify that inputing negative number into input field is displaying expected error " finished-at="2021-06-01T18:15:56 CEST" duration-ms="393" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[validateFactorialResults method failed due to: "" not matching expected: "Please enter an integer"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: validateFactorialResults method failed due to: "" not matching expected: "Please enter an integer"
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.assertTrue(Assert.java:41)
at pages.HomePage.validateFactorialResults(HomePage.java:111)
at tests.NegativeTestInputNegativeInteger.validateStringInputError(NegativeTestInputNegativeInteger.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateStringInputError -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.NegativeTestInputNegativeInteger@7e7be63f]" started-at="2021-06-01T18:15:56 CEST" name="tearDown" finished-at="2021-06-01T18:15:57 CEST" duration-ms="917" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.NegativeTestInputNegativeInteger -->
      <class name="tests.InputHappyPathIntegerAndValidateResult">
        <test-method is-config="true" signature="setup()[pri:0, instance:tests.InputHappyPathIntegerAndValidateResult@22ef9844]" started-at="2021-06-01T18:15:42 CEST" name="setup" finished-at="2021-06-01T18:15:45 CEST" duration-ms="2965" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="validateHappyPathIntegerAndResult()[pri:0, instance:tests.InputHappyPathIntegerAndValidateResult@22ef9844]" started-at="2021-06-01T18:15:45 CEST" name="validateHappyPathIntegerAndResult" description="Verify that Happy path with integer 10 is matching expected result" finished-at="2021-06-01T18:15:46 CEST" duration-ms="481" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateHappyPathIntegerAndResult -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.InputHappyPathIntegerAndValidateResult@22ef9844]" started-at="2021-06-01T18:15:46 CEST" name="tearDown" finished-at="2021-06-01T18:15:47 CEST" duration-ms="1160" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.InputHappyPathIntegerAndValidateResult -->
      <class name="tests.NaviagateToHomePageAndValidateStrings">
        <test-method is-config="true" signature="setup()[pri:0, instance:tests.NaviagateToHomePageAndValidateStrings@1a18644]" started-at="2021-06-01T18:15:47 CEST" name="setup" finished-at="2021-06-01T18:15:49 CEST" duration-ms="2030" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="validateElementsonHomePage()[pri:0, instance:tests.NaviagateToHomePageAndValidateStrings@1a18644]" started-at="2021-06-01T18:15:49 CEST" name="validateElementsonHomePage" description="Verify that all of the element Strings on the home page are matching expected Strings" finished-at="2021-06-01T18:15:49 CEST" duration-ms="432" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[ValidatePrivacyLinkString method failed due to string: "Terms and Conditions" not matching expected string: "Privacy"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: ValidatePrivacyLinkString method failed due to string: "Terms and Conditions" not matching expected string: "Privacy"
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.assertTrue(Assert.java:41)
at pages.HomePage.validateHomePagePrivacyLinkString(HomePage.java:69)
at tests.NaviagateToHomePageAndValidateStrings.validateElementsonHomePage(NaviagateToHomePageAndValidateStrings.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateElementsonHomePage -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.NaviagateToHomePageAndValidateStrings@1a18644]" started-at="2021-06-01T18:15:49 CEST" name="tearDown" finished-at="2021-06-01T18:15:51 CEST" duration-ms="1129" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.NaviagateToHomePageAndValidateStrings -->
    </test> <!-- FactorialTests -->
  </suite> <!-- Heartbeat -->
</testng-results>
